sudo: required

language: node_js

node_js:
- "8"

services:
- docker

before_install:
- sudo apt-get update
- sudo apt-get --yes --option Dpkg::Options::="--force-confnew" install docker-ce

script:
- npm install


services:
  - docker

ports:
- 80
